project:
  type: website
  output-dir: docs

toc: true
toc-depth: 3

format:
  html:
    theme: cerulean
    css: styles.css
    html-math-method: katex
    code-fold: false
    code-link: true
    code-copy: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    anchor-sections: true
    link-external-newwindow: true

execute:
  cache: true

website:
  title: "mizer course"
  site-url: "https://course.mizer.sizespectrum.org"
  favicon: images/favicon-16x16.png
  repo-url: https://github.com/sizespectrum/mizerCourse
  repo-actions: [edit, issue]
  twitter-card:
    site: "@mizer_model"
    creator: "gustavdelius"
  opengraph: true
  search: 
    location: navbar
    type: textbox
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Prepare"
        contents:
          - text: Introduce yourself
            href: prepare/introduce-yourself.qmd
          - text: Install tools
            href: prepare/install-tools.qmd
          - text: Use Git and GitHub
            href: prepare/use-git-and-github.qmd
          - text: Watch introduction
            href: prepare/watch-introduction.qmd
      - section: "Week 1: Understand"
        href: understand/index.qmd
        contents: 
          - text: Observed size spectra
            href: understand/observed-size-spectra.qmd
          - text: Single species spectra
            href: understand/single-species-spectra.qmd
          - text: Predation, growth and mortality
            href: understand/predation-growth-and-mortality.qmd
          - text: Dynamics of spectra
            href: understand/dynamics-of-spectra.qmd
          - text: Species interactions
            href: understand/species-interactions.qmd
      - section: "Week 2: Build"
        href: index.qmd
        contents:
          - text: Create first model
            href: build/create-first-model.qmd
          - text: Set multiple resources
            href: build/set-multiple-resources.qmd
          - text: Tune model
            href: build/tune-model.qmd
          - text: Find species parameters
            href: build/find-species-parameters.qmd
          - text: Build your own model
            href: build/build-your-own-model.qmd
      - section: "Week 3: Use"
        href: index.qmd
        contents:
          - text: Simulate change
            href: use/simulate-change.qmd
          - text: Refine model
            href: use/refine-model.qmd
          - text: Tune sensitivity
            href: use/tune-sensitivity.qmd
          - text: Change resources
            href: use/change-resources.qmd
          - text: Run your own scenarios
            href: use/run-your-own-scenarios.qmd


# comments:
#   giscus: 
#     repo: sizespectrum/mizerCourse
#     category: Comments
#     reactions-enabled: false
#     input-position: bottom
#     repo-id: R_kgDOHlJwYg
#     category-id: DIC_kwDOHlJwYs4CP_7j
#     data-loading: lazy
    
